#!/bin/bash
# Build figures/tree_viz_wasm.js: the REAL joint_lengths.c +
# huffman_table.c compiled to wasm32 (scalar path -- no __ARM_NEON /
# __SSE4_1__ on wasm), base64-embedded in a plain <script src>-loadable
# JS file so tree_viz.html keeps working from file://.
#
# Toolchain: homebrew llvm (clang with the wasm32 backend + wasm-ld).
# The only wasm import is env.log2, satisfied by Math.log2 in the
# loader below.
set -e
cd "$(dirname "$0")/../.."
CLANG=${CLANG:-/opt/homebrew/opt/llvm/bin/clang}
D=extras/tree_viz_wasm
OUT_WASM=$D/tree_viz.wasm
OUT_JS=figures/tree_viz_wasm.js

CFLAGS="--target=wasm32-unknown-unknown -O2 -ffreestanding -nostdlib
        -Iinclude -Isrc -I$D/include"

$CLANG $CFLAGS -fno-builtin -c $D/shim.c -o $D/shim.o
$CLANG $CFLAGS -c $D/viz.c            -o $D/viz.o
$CLANG $CFLAGS -c src/joint_lengths.c -o $D/joint_lengths.o
$CLANG $CFLAGS -c src/huffman_table.c -o $D/huffman_table.o

$CLANG --target=wasm32-unknown-unknown -nostdlib \
    -Wl,--no-entry -Wl,--allow-undefined -Wl,-z,stack-size=1048576 \
    $D/shim.o $D/viz.o $D/joint_lengths.o $D/huffman_table.o \
    -o $OUT_WASM

{
  echo "/* Generated by extras/tree_viz_wasm/build.sh -- do not edit."
  echo " * The real pivco joint_lengths.c + huffman_table.c as wasm32;"
  echo " * exports viz_plain_lengths / viz_joint_lengths (see viz.c). */"
  echo "window.PIVCO_WASM_B64 ="
  base64 -i $OUT_WASM | fold -w 96 | sed 's/.*/  "&" +/'
  echo '  "";'
  cat $D/loader.js
} > $OUT_JS

rm -f $D/*.o
ls -la $OUT_WASM $OUT_JS
